const COLORS={grid:'#2d2d33',current:'#80dfff',ma:'#afd485',upper:'#e070c0',lower:'#afd485',tqqq:'#e8714f',spym:'#b07cc0',sgov:'#5bb8e8',neutral:'#aaaaaa',fear:'#f0a0a0',extremeFear:'#e8714f',greed:'#5bb8e8',extremeGreed:'#b07cc0',white:'#fff',marker:'#ffd166'};
const $=id=>document.getElementById(id);
function fitCanvas(canvas){const ratio=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w:rect.width,h:rect.height};}
function chartGeometry(series,w,h,minOverride,maxOverride,showPriceAxis=false){const pad={l:10,r:showPriceAxis?66:10,t:18,b:20};const vals=series.flatMap(s=>s.values).filter(Number.isFinite);const min=minOverride??Math.min(...vals),max=maxOverride??Math.max(...vals),range=(max-min)||1;return{pad,min,max,range,x:(i,n)=>pad.l+(i/(n-1||1))*(w-pad.l-pad.r),y:v=>h-pad.b-((v-min)/range)*(h-pad.t-pad.b)};}
function drawLineChart(canvas,series,options={}){const {ctx,w,h}=fitCanvas(canvas);ctx.clearRect(0,0,w,h);const g=chartGeometry(series,w,h,options.min,options.max,options.showPriceAxis);[.25,.5,.75].forEach(p=>{const gridY=g.pad.t+(h-g.pad.t-g.pad.b)*p;ctx.strokeStyle=COLORS.grid;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(g.pad.l,gridY);ctx.lineTo(w-g.pad.r,gridY);ctx.stroke();if(options.showPriceAxis){const tickValue=g.max-p*g.range;ctx.fillStyle='rgba(220,220,228,.78)';ctx.font='600 11px Arial';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(`$${tickValue.toFixed(2)}`,w-g.pad.r+8,gridY);}});if(options.showPriceAxis){ctx.strokeStyle='rgba(90,90,100,.65)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(w-g.pad.r,g.pad.t);ctx.lineTo(w-g.pad.r,h-g.pad.b);ctx.stroke();}series.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=s.width||2;ctx.beginPath();let started=false;s.values.forEach((v,i)=>{if(!Number.isFinite(v))return;const x=g.x(i,s.values.length),y=g.y(v);if(!started){ctx.moveTo(x,y);started=true}else ctx.lineTo(x,y)});ctx.stroke();});if(options.marker&&Number.isInteger(options.marker.index)){const m=options.marker,n=series[0].values.length,x=g.x(m.index,n),y=g.y(m.value);ctx.save();ctx.strokeStyle=COLORS.marker;ctx.fillStyle=COLORS.marker;ctx.lineWidth=1.5;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(x,g.pad.t);ctx.lineTo(x,h-g.pad.b);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(x,y,5.5,0,Math.PI*2);ctx.fill();ctx.font='700 11px Arial';ctx.textAlign=x>w*.72?'right':'left';ctx.fillText(m.label,x+(x>w*.72?-7:7),Math.max(13,y-10));ctx.restore();}}
function fgiColor(v){if(v>=75)return COLORS.extremeGreed;if(v>=55)return COLORS.greed;if(v>=45)return COLORS.neutral;if(v>=25)return COLORS.fear;return COLORS.extremeFear}
function drawFgiChart(canvas,values){drawLineChart(canvas,[{values,color:'rgba(255,255,255,.45)',width:2}],{min:0,max:100});const {ctx,w,h}=fitCanvas(canvas),pad={l:10,r:10,t:18,b:20};values.forEach((v,i)=>{const x=pad.l+(i/(values.length-1||1))*(w-pad.l-pad.r),y=h-pad.b-(v/100)*(h-pad.t-pad.b);ctx.fillStyle=fgiColor(v);ctx.beginPath();ctx.arc(x,y,3.2,0,Math.PI*2);ctx.fill();});}
function drawGauge(canvas,value){const {ctx,w,h}=fitCanvas(canvas);ctx.clearRect(0,0,w,h);const cx=w/2,cy=h*.92,r=Math.min(w*.42,h*.78);for(let i=0;i<120;i++){const t=i/119,a=Math.PI+t*Math.PI;ctx.fillStyle=fgiColor(t*100);ctx.beginPath();ctx.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r,4.6,0,Math.PI*2);ctx.fill();}const a=Math.PI+(value/100)*Math.PI;ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*(r-7),cy+Math.sin(a)*(r-7));ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(cx,cy,6,0,Math.PI*2);ctx.fill();}
function tokenClass(name){return name==='TQQQ'?'token-tqqq':name==='SPYM'?'token-spym':name==='SGOV'?'token-sgov':''}
function renderActions(target,lines,isAlert=false){target.innerHTML='';lines.forEach(([asset,action])=>{const row=document.createElement('div');row.className='action-line'+(isAlert?' alert':'');asset.split('·').forEach((part,i)=>{const span=document.createElement('span');span.className=tokenClass(part);span.textContent=part;row.appendChild(span);if(i<asset.split('·').length-1)row.append('·')});const actionSpan=document.createElement('span');actionSpan.textContent=action;row.appendChild(actionSpan);target.appendChild(row);});}
function money(v){return Number.isFinite(v)?`$${v.toFixed(2)}`:'-'}
function renderProfitAlert(p){const el=$('profitAlert');if(!p||!p.triggered){el.className='profit-alert hidden';el.textContent='';return;}el.className=`profit-alert ${p.type==='major'?'major':'minor'}`;el.innerHTML=`<span>${p.type==='major'?'대익절':'소익절'}</span><strong>수익률 +${p.level}% 달성</strong><em>현재 잔고의 ${p.sell_pct}% 판매 → SPYM 전환</em>`;}
async function load(){try{const res=await fetch(`data/latest.json?v=${Date.now()}`);if(!res.ok)throw new Error(`HTTP ${res.status}`);const d=await res.json();$('updatedAt').textContent=`최종 갱신: ${d.updated_at_kst}`;$('marketDate').textContent=`${d.market_date} 미국장 종가 기준`;
const beta=d.beta;renderActions($('betaActions'),beta.signal.lines,beta.signal.is_alert);$('betaStatus').textContent=beta.signal.name;$('betaStatus').classList.toggle('alert',beta.signal.is_alert);$('drawdown').textContent=beta.signal.drawdown_text;$('qqqPrice').textContent=money(beta.current_price);$('qqqSma').textContent=money(beta.sma_200);renderProfitAlert(beta.profit_alert);$('breakoutInfo').innerHTML=beta.breakout?`<b>${beta.breakout.date} 상단 밴드 돌파</b><br>TQQQ 기준가 ${money(beta.breakout.tqqq_price)} · 현재 수익률 ${beta.breakout.return_pct>=0?'+':''}${beta.breakout.return_pct.toFixed(1)}%<br><small>다음 익절 목표: ${beta.profit_alert?.next_level?`+${beta.profit_alert.next_level}%`:'없음'}</small>`:'최근 상단 밴드 돌파 기록 없음';
const drawBeta=()=>drawLineChart($('betaChart'),[{values:beta.upper,color:COLORS.upper,width:2},{values:beta.lower,color:COLORS.lower,width:2},{values:beta.prices,color:COLORS.current,width:3}],{showPriceAxis:true,marker:beta.breakout?.chart_index>=0?{index:beta.breakout.chart_index,value:beta.breakout.qqq_price,label:beta.breakout.date.slice(5)}:null});drawBeta();
const old=d.old;renderActions($('oldActions'),old.signal.lines);$('oldStatus').textContent=`${old.signal.name} (${old.gap_pct>=0?'+':''}${old.gap_pct.toFixed(2)}%)`;$('tqqqPrice').textContent=money(old.current_price);$('tqqqSma').textContent=money(old.sma_200);const drawOld=()=>drawLineChart($('oldChart'),[{values:old.sma,color:COLORS.ma,width:2.5},{values:old.prices,color:COLORS.current,width:3}],{showPriceAxis:true});drawOld();
const f=d.fgi;$('fgiValue').textContent=Math.round(f.current);$('fgiValue').style.color=fgiColor(f.current);$('fgiRating').textContent=f.rating_ko;$('fgiRating').style.color=fgiColor(f.current);$('fgiNow').textContent=`현재 ${Math.round(f.current)}`;$('fgiAvg').textContent=`30일 평균 ${Math.round(f.average_30)}`;$('fgiNow').style.color=fgiColor(f.current);$('fgiAvg').style.color=fgiColor(f.average_30);const drawF=()=>{drawGauge($('gauge'),f.current);drawFgiChart($('fgiChart'),f.values)};drawF();let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>{drawBeta();drawOld();drawF();},120)},{passive:true});}catch(e){document.querySelector('.grid').innerHTML=`<article class="card card-wide error">데이터를 불러오지 못했습니다.<br>${e.message}</article>`;}}
load();